language: cpp

matrix:
    include:
        - os: windows
          script:
            - export PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin":$PATH
            - export DSN_AUTO_TEST=1
            - export DSN_TRAVIS=1
            - ./run.cmd setup-env
            - ./run.cmd build Debug builddbg
            - ./run.cmd install Debug builddbg
            - ./run.cmd start_zk
            - ./run.cmd test Debug builddbg
        - os: linux
          sudo: required
          dist: xenial
          before_install:
            - sudo apt-get install -y wget mono-xbuild libaio-dev
            - sudo apt-get install -y --no-install-recommends libboost-all-dev
          script:
            - ./run.sh format
            - ulimit -c unlimited -S
            - this_path=`readlink -f $0`
            - export DSN_ROOT=`dirname $this_path`
            - ./run.sh build --build_plugins
            - ./run.sh install
            - ./run.sh start_zk
            - ./run.sh test        


notifications:
  email: false
