sudo: required
dist: xenial

language: cpp

os: linux

compiler: 
    - gcc

before_install:
    - sudo apt-get install -y build-essential cmake mono-xbuild php-cli
    - sudo apt-get install -y --no-install-recommends libboost-all-dev

install:
    - ./run.sh format

before_script:
    - ./run.sh start_zk
    - ulimit -c unlimited -S

script:
    - this_path=`readlink -f $0`
    - export DSN_ROOT=`dirname $this_path`
    - ./run.sh build --build_plugins    
    - ./run.sh install
    - ./run.sh test

notifications:
  email: false
