language: cpp

matrix:
    include:
        - os: windows
          install:
            - choco install jdk8 -params "source=false"
          script:
            - export PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin":"c/ProgramData/chocolatey/bin":$PATH
            - export DSN_AUTO_TEST=1
            - export DSN_TRAVIS=1
            - git config --global user.name "travis"
            - git config --global user.email ""
            - ./run.cmd setup-env
            - ./run.cmd build RelWithDebInfo builder build_plugins
            - ./run.cmd install RelWithDebInfo builder
            - ./run.cmd start_zk
            - ./run.cmd test RelWithDebInfo builder
            - ./run.cmd stop_zk
        - os: linux
          sudo: required
          dist: xenial
          before_install:
            - sudo apt-get install -y wget mono-xbuild libaio-dev
            - sudo apt-get install -y --no-install-recommends libboost-all-dev
          script:
            - ./run.sh format
            - ulimit -c unlimited -S
            - this_path=`readlink -f $0`
            - export DSN_ROOT=`dirname $this_path`
            - ./run.sh build --build_plugins
            - ./run.sh install
            - ./run.sh start_zk
            - ./run.sh test
            - ./run.sh stop_zk


notifications:
  email: false
