var dsn_types_global = typeof globalThis !== 'undefined' ? globalThis :
    (typeof window !== 'undefined' ? window :
    (typeof self !== 'undefined' ? self :
    (typeof global !== 'undefined' ? global : null)));
var dsn_types_commonjs =
    typeof module !== 'undefined' && module.exports &&
    typeof require === 'function';
var dsn_types_runtime = null;
var Thrift;
var DSN;
if (dsn_types_commonjs) {
  dsn_types_runtime = require('./dsn_transport.js');
  Thrift = dsn_types_runtime.Thrift;
  DSN = dsn_types_runtime.DSN;
} else {
  Thrift = dsn_types_global && dsn_types_global.Thrift;
  DSN = dsn_types_global && dsn_types_global.DSN;
}
if (!Thrift || !DSN) {
  throw new Error('dsn_types.js requires thrift.js and dsn_transport.js');
}

var error_code;
var task_code;
var gpid;
var blob;
var rpc_address;

//
// Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


error_code = function(args) {
  this.code = 'ERR_OK';
  if (typeof args === 'string') {
    this.code = error_code._code(args);
  } else if (args) {
    if (args.code !== undefined && args.code !== null) {
      this.code = error_code._code(args.code);
    }
  }
};
error_code.prototype = {};
error_code._code = function(value) {
  if (typeof value !== 'string' || value.length === 0) {
    throw new TypeError('error_code must be a non-empty string');
  }
  return value;
};
error_code.prototype.toString = function() {
  return this.code;
};
error_code.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.code = error_code._code(input.readString().value);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

error_code.prototype.write = function(output) {
  output.writeStructBegin('error_code');
  if (this.code !== null && this.code !== undefined) {
    output.writeFieldBegin('code', Thrift.Type.STRING, 1);
    output.writeString(this.code);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

task_code = function(args) {
  this.code = 'TASK_CODE_INVALID';
  if (typeof args === 'string') {
    this.code = task_code._code(args);
  } else if (args) {
    if (args.code !== undefined && args.code !== null) {
      this.code = task_code._code(args.code);
    }
  }
};
task_code.prototype = {};
task_code._code = function(value) {
  if (typeof value !== 'string' || value.length === 0) {
    throw new TypeError('task_code must be a non-empty string');
  }
  return value;
};
task_code.prototype.toString = function() {
  return this.code;
};
task_code.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.code = task_code._code(input.readString().value);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

task_code.prototype.write = function(output) {
  output.writeStructBegin('task_code');
  if (this.code !== null && this.code !== undefined) {
    output.writeFieldBegin('code', Thrift.Type.STRING, 1);
    output.writeString(this.code);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

gpid = function(args) {
  this.id = 0;
  if (args !== undefined && args !== null && typeof args !== 'object') {
    this.id = Thrift.Int64.normalizeSigned(args, true);
  } else if (args) {
    if (args.id !== undefined && args.id !== null) {
      this.id = Thrift.Int64.normalizeSigned(args.id, true);
    } else if (args.app_id !== undefined || args.partition_index !== undefined) {
      this.id = gpid.make_id(
        args.app_id === undefined ? 0 : args.app_id,
        args.partition_index === undefined ? 0 : args.partition_index);
    }
  }
};
gpid.prototype = {};

gpid._int32 = function(value, name) {
  var number = Number(value);
  if (!isFinite(number) || Math.floor(number) !== number ||
      number < -2147483648 || number > 2147483647) {
    throw new RangeError(name + ' must be a signed 32-bit integer');
  }
  return number;
};

gpid.make_id = function(app_id, partition_index) {
  var appId = gpid._int32(app_id, 'app_id') >>> 0;
  var partitionIndex = gpid._int32(partition_index, 'partition_index') >>> 0;
  return Thrift.Int64.normalizeSigned(
    Thrift.Int64.fromParts(partitionIndex, appId, true), false);
};

gpid.from = function(app_id, partition_index) {
  return new gpid({ app_id: app_id, partition_index: partition_index });
};

gpid.prototype.app_id = function() {
  return Thrift.Int64.toParts(this.id, true).low | 0;
};

gpid.prototype.partition_index = function() {
  return Thrift.Int64.toParts(this.id, true).high | 0;
};

gpid.prototype.get_app_id = function() {
  return this.app_id();
};

gpid.prototype.get_partition_index = function() {
  return this.partition_index();
};

gpid.prototype.set_app_id = function(value) {
  this.id = gpid.make_id(value, this.partition_index());
};

gpid.prototype.set_partition_index = function(value) {
  this.id = gpid.make_id(this.app_id(), value);
};

gpid.prototype.toString = function() {
  return this.app_id() + "." + this.partition_index();
};

gpid.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I64) {
        this.id = Thrift.Int64.normalizeSigned(input.readI64().value, false);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

gpid.prototype.write = function(output) {
  output.writeStructBegin('gpid');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.I64, 1);
    output.writeI64(this.id);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

blob = function(args) {
  this.data = '';
  if (typeof args === 'string') {
    this.data = args;
  } else if (typeof Uint8Array !== 'undefined' && args instanceof Uint8Array) {
    this.data = args;
  } else if (typeof ArrayBuffer !== 'undefined' && args instanceof ArrayBuffer) {
    this.data = new Uint8Array(args);
  } else if (args) {
    if (args.data !== undefined && args.data !== null) {
      this.data = args.data;
    }
  }
};
blob.prototype = {};
blob.prototype.read = function(input) {
  this.data = input.readBinary().value;
  return;
};

blob.prototype.write = function(output) {
  output.writeBinary(this.data === null || this.data === undefined ? '' : this.data);
  return;
};

blob.prototype.toString = function() {
  return this.data === null || this.data === undefined ? '' : this.data;
};

rpc_address = function(args) {
  this.host = 'invalid address';
  this.port = 0;
  if (typeof args === 'string') {
    var index = args.lastIndexOf(':');
    if (index >= 0) {
      this.host = rpc_address._host(args.substring(0, index));
      this.port = rpc_address._port(args.substring(index + 1));
    } else {
      this.host = rpc_address._host(args);
    }
  } else if (args) {
    if (args.host !== undefined && args.host !== null) {
      this.host = rpc_address._host(args.host);
    }
    if (args.port !== undefined && args.port !== null) {
      this.port = rpc_address._port(args.port);
    }
  }
};
rpc_address.prototype = {};
rpc_address._host = function(value) {
  if (typeof value !== 'string' || value.length === 0) {
    throw new TypeError('host must be a non-empty string');
  }
  return value;
};
rpc_address._port = function(value) {
  var port = Number(value);
  if (!isFinite(port) || Math.floor(port) !== port || port < 0 || port > 65535) {
    throw new RangeError('port must be an unsigned 16-bit integer');
  }
  return port;
};
rpc_address.prototype.toString = function() {
  if (this.host === 'invalid address' && this.port === 0) {
    return this.host;
  }
  return this.host + ':' + this.port;
};
rpc_address.prototype.is_invalid = function() {
  return this.host === 'invalid address' && this.port === 0;
};
rpc_address.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.host = rpc_address._host(input.readString().value);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.port = rpc_address._port(input.readI32().value);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

rpc_address.prototype.write = function(output) {
  output.writeStructBegin('rpc_address');
  if (this.host !== null && this.host !== undefined) {
    output.writeFieldBegin('host', Thrift.Type.STRING, 1);
    output.writeString(this.host);
    output.writeFieldEnd();
  }
  if (this.port !== null && this.port !== undefined) {
    output.writeFieldBegin('port', Thrift.Type.I32, 2);
    output.writeI32(this.port);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var dsn_types_exports = {
  error_code: error_code,
  task_code: task_code,
  gpid: gpid,
  blob: blob,
  rpc_address: rpc_address
};

DSN.register_types(dsn_types_exports);

if (dsn_types_commonjs) {
  module.exports = dsn_types_exports;
} else if (dsn_types_global) {
  for (var dsn_type_name in dsn_types_exports) {
    if (Object.prototype.hasOwnProperty.call(dsn_types_exports, dsn_type_name)) {
      dsn_types_global[dsn_type_name] = dsn_types_exports[dsn_type_name];
    }
  }
}
